// Design philosophy: 車庫晨光。英文版延續 Roadi 的溫暖紙白、深墨綠、Safety Orange 與路線清單，確保雙語政策具一致品牌體驗。
import { ArrowUpRight, CarFront, Check, ChevronRight, Mail, ShieldCheck } from "lucide-react";

const sections = [
  ["data", "01", "What data does Roadi process?"], ["account", "02", "No user account required"], ["not-collect", "03", "Data Roadi does not actively collect"], ["local", "04", "Local data storage"], ["export", "05", "Export, import and sharing"], ["notification", "06", "Notifications"], ["third-party", "07", "Third-party software and services"], ["sharing", "08", "Data sharing and sale"], ["retention", "09", "Data retention and deletion"], ["security", "10", "Data security"], ["children", "11", "Children’s privacy"], ["changes", "12", "Changes to this policy"], ["contact", "13", "Contact us"], ["scope", "14", "Scope"],
];
const BulletList = ({ items }: { items: string[] }) => <ul className="policy-list">{items.map((item) => <li key={item}><span className="list-check"><Check size={13} strokeWidth={3} /></span><span>{item}</span></li>)}</ul>;

export default function EnglishPolicy() {
  const jumpTo = (id: string) => document.getElementById(id)?.scrollIntoView({ behavior: "smooth", block: "start" });
  return <div className="site-shell">
    <header className="topbar"><a className="brand" href="/" aria-label="Roadi home"><img src="/manus-storage/roadi-mark_5db22b61.png" alt="" className="brand-mark" /><span><strong>Roadi</strong><small>路迪｜車管家</small></span></a><div className="topbar-meta"><span className="status-dot" /> Privacy policy <span className="meta-divider" /> 2026.08 <a className="language-switch" href="/">中文</a></div><a className="language-switch mobile-language" href="/">中文</a></header>
    <main id="top">
      <section className="hero-section"><div className="hero-copy"><div className="eyebrow"><span className="eyebrow-line" /> DOCUMENT / PRIVACY</div><h1>Keep your data<br /><em>in your own garage.</em></h1><p className="hero-lede">Roadi is designed local-first. Your vehicle records stay on your device, with a clear explanation of how every piece of data is handled.</p><div className="hero-details"><span>Last updated</span><strong>August 26, 2026</strong><span className="detail-rule" /><span>Platform</span><strong>Android App</strong></div></div><div className="hero-visual" aria-hidden="true"><img src="/manus-storage/roadi-policy-hero_8d71e61f.jpg" alt="" /><div className="hero-stamp">LOCAL<br /><span>FIRST</span></div><div className="road-mark" /></div></section>
      <section className="intro-band"><div className="intro-icon"><ShieldCheck size={25} /></div><p><strong>We respect your privacy.</strong> This policy explains how Roadi handles data generated, entered, or used while you use the App. Core vehicle data is stored locally on your device. Roadi does not require an account and does not actively upload your records to servers operated by the developer.</p><ArrowUpRight size={21} className="intro-arrow" /></section>
      <div className="policy-layout"><aside className="section-nav" aria-label="Policy sections"><div className="nav-kicker">ON THIS PAGE</div><div className="nav-list">{sections.map(([id, number, label]) => <button key={id} onClick={() => jumpTo(id)}><span>{number}</span>{label}<ChevronRight size={14} /></button>)}</div><div className="nav-note"><CarFront size={17} /><span>Your data stays local<br />by default.</span></div></aside>
      <article className="policy-content"><div className="content-label"><span>ROADi / PRIVACY POLICY</span><span>REV. 01 / EN</span></div>
        <section className="policy-section" id="data"><div className="section-heading"><span>01</span><h2>What data does Roadi process?</h2></div><p>To provide vehicle management, refuelling records, maintenance records, expense summaries and reminders, you may voluntarily enter or create the following data in Roadi:</p><BulletList items={["Vehicle name or nickname", "License plate or vehicle number", "Vehicle type", "Purchase date", "Mileage at purchase", "Current mileage", "Refuelling date", "Fuel quantity", "Fuel cost", "Station or merchant name", "Maintenance and repair records", "Custom maintenance items", "Other vehicle expenses", "Notes", "Other vehicle-management information you voluntarily enter"]} /><p>This data is primarily stored in the local database on your device. Roadi does not actively transmit the vehicle data listed above to servers operated by the developer.</p></section>
        <section className="policy-section" id="account"><div className="section-heading"><span>02</span><h2>No user account required</h2></div><p>Roadi’s core features do not require you to create an account or sign in. Roadi does not ask you to provide:</p><BulletList items={["A user account", "A password", "Login credentials", "A personal social-media account"]} /><p>Accordingly, the developer does not maintain a Roadi user-account database.</p></section>
        <section className="policy-section" id="not-collect"><div className="section-heading"><span>03</span><h2>Data Roadi does not actively collect</h2></div><p>Roadi does not actively collect the following data for its core features:</p><BulletList items={["GPS or precise location information", "Contacts", "Photos or videos", "Microphone recordings", "Phone calls or text messages", "Health information", "Credit-card or payment information", "Advertising identifiers", "User-account or login information"]} /><p>Roadi does not use GPS to track your driving location.</p></section>
        <section className="policy-section" id="local"><div className="section-heading"><span>04</span><h2>Local data storage</h2></div><p>Roadi uses the local database on your device to store your vehicle and related records. Your core vehicle data is therefore not stored on Roadi cloud servers.</p><div className="callout"><strong>Please back up important data</strong><p>If you uninstall Roadi, clear App data, reset your device, or local data is removed due to device or operating-system circumstances, data that has not been exported or backed up may be lost. We recommend using Roadi’s export or backup features regularly.</p></div></section>
        <section className="policy-section" id="export"><div className="section-heading"><span>05</span><h2>Export, import and sharing</h2></div><p>Roadi provides export and backup features, including formats such as Excel and JSON. When you voluntarily use sharing, storage or cloud services provided by Android or another operating system, the third party you choose may receive the data you intentionally share.</p><p>Examples include Google Drive, email services, messaging apps, and other file-storage or sharing services. This transfer occurs because of your active choice and operation. Please refer to the privacy policy of the relevant third party for how it handles the data you provide.</p></section>
        <section className="policy-section" id="notification"><div className="section-heading"><span>06</span><h2>Notifications</h2></div><p>Roadi may use Android notifications to remind you about vehicle maintenance items that are approaching or past their due dates. Notification content is generated mainly from vehicle and maintenance data you create in Roadi. Roadi does not collect personal data through notifications. You can manage Roadi’s notification permission in Android system settings.</p></section>
        <section className="policy-section" id="third-party"><div className="section-heading"><span>07</span><h2>Third-party software and services</h2></div><p>Roadi uses necessary third-party software packages and platform components to support App operation, data storage, notifications, file handling and other essential functions. Roadi does not use third-party advertising services and does not sell your vehicle or personal data. If the third-party software or services used by the App materially change in the future, this privacy policy may be updated accordingly.</p></section>
        <section className="policy-section" id="sharing"><div className="section-heading"><span>08</span><h2>Data sharing and sale</h2></div><p>Roadi does not sell, rent or provide your vehicle data to third parties for advertising or marketing purposes, and does not actively share your vehicle records with other companies or organizations. When you voluntarily use an export, sharing, storage or backup feature, data may be sent to the third-party service you select based on your action.</p><p>That third party’s handling of the data is governed by its own privacy policy and terms of service.</p></section>
        <section className="policy-section" id="retention"><div className="section-heading"><span>09</span><h2>Data retention and deletion</h2></div><p>Roadi’s vehicle and related records are primarily stored locally on your device. You can delete vehicles and related records directly in Roadi. To remove Roadi data stored on your device, use Android’s “Clear App data” function or uninstall Roadi.</p><p>Because Roadi does not use user accounts, there is no developer-managed account or account-deletion process. The developer does not retain an independent copy of Roadi vehicle data.</p></section>
        <section className="policy-section" id="security"><div className="section-heading"><span>10</span><h2>Data security</h2></div><p>Roadi’s local-storage design reduces the need to transmit vehicle data to external servers. However, no electronic storage method can guarantee absolute security. You should protect your device, operating system and exported files, and regularly back up important information.</p><p>When you give exported Roadi data to a third-party service for storage or sharing, its security and handling are subject to that service’s security measures and privacy policy.</p></section>
        <section className="policy-section" id="children"><div className="section-heading"><span>11</span><h2>Children’s privacy</h2></div><p>Roadi is not specifically designed for children. Roadi does not actively collect children’s personal data.</p></section>
        <section className="policy-section" id="changes"><div className="section-heading"><span>12</span><h2>Changes to this policy</h2></div><p>We may update this privacy policy due to changes in App features, data handling, third-party services or applicable laws. The updated version will be published on this page and the “Last updated” date will be changed. If there is a material change, we will provide appropriate notice within a reasonable scope.</p></section>
        <section className="policy-section contact-section" id="contact"><div className="section-heading"><span>13</span><h2>Contact us</h2></div><p>If you have questions about this privacy policy, Roadi’s data practices or your privacy rights, please contact us.</p><div className="contact-card"><div className="contact-card-icon"><Mail size={22} /></div><div><span>App</span><strong>Roadi路迪｜車管家</strong><span>Developer</span><strong>Billy Song</strong><a href="mailto:attila700@yahoo.com.tw">attila700@yahoo.com.tw <ArrowUpRight size={15} /></a></div></div></section>
        <section className="policy-section" id="scope"><div className="section-heading"><span>14</span><h2>Scope</h2></div><p>This privacy policy applies to the Roadi路迪｜車管家 Android App. It does not apply to third-party services that you voluntarily use through Roadi, such as Google Drive, email, messaging or other file-sharing and storage services. Those services are governed by their respective privacy policies and terms of service.</p></section>
        <footer className="policy-footer"><span>© 2026 Billy Song. All rights reserved.</span><span>ROADi / LOCAL-FIRST VEHICLE CARE</span></footer>
      </article></div>
    </main>
  </div>;
}
