// Design philosophy: 車庫晨光。英文版延續 Roadi 的溫暖紙白、深墨綠、Safety Orange 與路線清單，確保雙語政策具一致品牌體驗。
import { ArrowUpRight, CarFront, Check, ChevronRight, Mail, ShieldCheck } from "lucide-react";

const sections = [
  ["data", "01", "What Information Does Roadi Handle?"], ["account", "02", "No User Account Required"], ["not-collect", "03", "Information Roadi Does Not Actively Collect"], ["local", "04", "Local Data Storage"], ["export", "05", "Data Export, Import, and Sharing"], ["notification", "06", "Notifications"], ["third-party", "07", "Third-Party Software and Services"], ["sharing", "08", "Data Sharing and Sale"], ["retention", "09", "Data Retention and Deletion"], ["security", "10", "Data Security"], ["children", "11", "Children's Privacy"], ["changes", "12", "Changes to This Privacy Policy"], ["contact", "13", "Contact Us"], ["scope", "14", "Scope"],
];
const BulletList = ({ items }: { items: string[] }) => <ul className="policy-list">{items.map((item) => <li key={item}><span className="list-check"><Check size={13} strokeWidth={3} /></span><span>{item}</span></li>)}</ul>;

export default function EnglishPolicy() {
  const jumpTo = (id: string) => document.getElementById(id)?.scrollIntoView({ behavior: "smooth", block: "start" });
  return <div className="site-shell">
    <header className="topbar"><a className="brand" href="/" aria-label="Roadi home"><img src="/manus-storage/roadi-mark_5db22b61.png" alt="" className="brand-mark" /><span><strong>Roadi</strong><small>Vehicle Companion</small></span></a><div className="topbar-meta"><span className="status-dot" /> Privacy policy <span className="meta-divider" /> 2026.08 <a className="language-switch" href="/">中文</a></div><a className="language-switch mobile-language" href="/">中文</a></header>
    <main id="top">
      <section className="hero-section"><div className="hero-copy"><div className="eyebrow"><span className="eyebrow-line" /> DOCUMENT / PRIVACY</div><h1>Keep your data<br /><em>in your own garage.</em></h1><p className="hero-lede">Roadi follows a “Local-First” design approach. Your vehicle data is primarily stored on your device, with a clear explanation of how every piece of information is handled.</p><div className="hero-details"><span>Last updated</span><strong>August 26, 2026</strong><span className="detail-rule" /><span>Platform</span><strong>Android App</strong></div></div><div className="hero-visual" aria-hidden="true"><img src="/manus-storage/roadi-policy-hero_8d71e61f.jpg" alt="" /><div className="hero-stamp">LOCAL<br /><span>FIRST</span></div><div className="road-mark" /></div></section>
      <section className="intro-band"><div className="intro-icon"><ShieldCheck size={25} /></div><p><strong>We respect your privacy.</strong> This Privacy Policy explains how Roadi handles information that is generated, entered, or used when you use the App. Roadi does not require you to create a user account and does not actively upload your vehicle records to servers operated by the Developer.</p><ArrowUpRight size={21} className="intro-arrow" /></section>
      <div className="policy-layout"><aside className="section-nav" aria-label="Policy sections"><div className="nav-kicker">ON THIS PAGE</div><div className="nav-list">{sections.map(([id, number, label]) => <button key={id} onClick={() => jumpTo(id)}><span>{number}</span>{label}<ChevronRight size={14} /></button>)}</div><div className="nav-note"><CarFront size={17} /><span>Your data stays local<br />by default.</span></div></aside>
      <article className="policy-content"><div className="content-label"><span>ROADi / PRIVACY POLICY</span><span>REV. 01 / EN</span></div>
        <section className="policy-section" id="data"><div className="section-heading"><span>01</span><h2>What Information Does Roadi Handle?</h2></div><p>To provide vehicle management, fuel tracking, maintenance records, expense tracking, statistics, and reminder features, you may voluntarily enter or create the following information in Roadi:</p><BulletList items={["Vehicle name or nickname", "License plate or vehicle number", "Vehicle type", "Purchase date", "Mileage at purchase", "Current mileage", "Fueling date", "Fuel amount", "Fueling cost", "Fuel station or store name", "Maintenance and repair records", "Custom maintenance items", "Other vehicle-related expenses", "Notes", "Other vehicle management information that you voluntarily enter"]} /><p>This information is primarily stored in a local database on your device.</p><p>Roadi does not actively transmit these vehicle records to servers operated by the Developer.</p></section>
        <section className="policy-section" id="account"><div className="section-heading"><span>02</span><h2>No User Account Required</h2></div><p>Roadi does not require you to create an account or sign in to use its main features.</p><p>Roadi does not require you to provide:</p><BulletList items={["A user account", "A password", "Login credentials", "A social media account"]} /><p>Roadi therefore does not maintain a user account database operated by the Developer.</p></section>
        <section className="policy-section" id="not-collect"><div className="section-heading"><span>03</span><h2>Information Roadi Does Not Actively Collect</h2></div><p>Roadi does not actively collect the following information for its main functionality:</p><BulletList items={["GPS or precise location data", "Contacts", "Photos or videos", "Microphone or audio recordings", "Calls or SMS", "Health information", "Credit card or payment information", "Advertising identifiers", "User account or login information"]} /><p>Roadi does not use GPS to track your driving or travel locations.</p></section>
        <section className="policy-section" id="local"><div className="section-heading"><span>04</span><h2>Local Data Storage</h2></div><p>Roadi stores your vehicle and related records in a local database on your device.</p><p>Your primary vehicle data is therefore not stored on Roadi cloud servers.</p><div className="callout"><strong>Please back up important data</strong><p>If you uninstall Roadi, clear the App's data, reset your device, or lose local data due to device or operating system behavior, any data that has not been exported or backed up may be lost. We recommend regularly exporting or backing up important information.</p></div></section>
        <section className="policy-section" id="export"><div className="section-heading"><span>05</span><h2>Data Export, Import, and Sharing</h2></div><p>Roadi provides data export and backup features, including formats such as Excel and JSON.</p><p>When you voluntarily use Android or another operating system's sharing, storage, or cloud services, the third-party service you choose may receive the data you intentionally share.</p><p>Examples include:</p><BulletList items={["Google Drive", "Email services", "Messaging applications", "Other file storage or sharing services"]} /><p>These transfers are initiated through your actions and your selection of the third-party service.</p><p>Roadi does not automatically upload your data to servers operated by the Developer when you use the export function.</p><p>Please refer to the privacy policy of the third-party service you choose for information about how that service handles your data.</p></section>
        <section className="policy-section" id="notification"><div className="section-heading"><span>06</span><h2>Notifications</h2></div><p>Roadi may use Android's notification functionality to remind you about vehicle maintenance items that are due or approaching their maintenance interval.</p><p>Notification content is primarily generated from vehicle and maintenance information stored in Roadi.</p><p>Roadi does not collect personal information through notifications.</p><p>You can manage Roadi's notification permissions through your Android system settings.</p></section>
        <section className="policy-section" id="third-party"><div className="section-heading"><span>07</span><h2>Third-Party Software and Services</h2></div><p>Roadi uses necessary third-party software libraries and platform components to support the operation of the App, local data storage, notifications, file handling, and other required functionality.</p><p>Roadi does not use third-party advertising services.</p><p>Roadi does not sell your vehicle data or personal information.</p><p>If the third-party software or services used by Roadi materially change in the future, this Privacy Policy may be updated accordingly.</p></section>
        <section className="policy-section" id="sharing"><div className="section-heading"><span>08</span><h2>Data Sharing and Sale</h2></div><p>Roadi does not sell, rent, or provide your vehicle data to third parties for advertising or marketing purposes.</p><p>Roadi does not actively share your vehicle records with other companies or organizations.</p><p>When you voluntarily use export, sharing, storage, or backup functionality, your data may be transferred to the third-party service you select.</p><p>The handling of your data by such third-party services is governed by their respective privacy policies and terms of service.</p></section>
        <section className="policy-section" id="retention"><div className="section-heading"><span>09</span><h2>Data Retention and Deletion</h2></div><p>Your vehicle and related records are primarily stored locally on your device.</p><p>You can delete vehicles and related records directly within Roadi.</p><p>If you want to remove Roadi's locally stored data from your device, you can use Android's “Clear App Data” functionality or uninstall Roadi.</p><p>Because Roadi does not use user accounts, there is no account or account-deletion process managed by the Developer.</p><p>The Developer does not maintain a separate copy of your Roadi vehicle records.</p></section>
        <section className="policy-section" id="security"><div className="section-heading"><span>10</span><h2>Data Security</h2></div><p>Roadi uses a local-storage design to minimize the need to transmit vehicle data to external servers.</p><p>However, no electronic storage method can be guaranteed to be completely secure.</p><p>You should properly protect your device, operating system, and exported files. We also recommend regularly backing up important information.</p><p>When you store or share exported Roadi data through a third-party service, the security and handling of that data are governed by that third party's security practices and privacy policy.</p></section>
        <section className="policy-section" id="children"><div className="section-heading"><span>11</span><h2>Children's Privacy</h2></div><p>Roadi is not specifically designed for children.</p><p>Roadi does not knowingly collect personal information from children.</p></section>
        <section className="policy-section" id="changes"><div className="section-heading"><span>12</span><h2>Changes to This Privacy Policy</h2></div><p>We may update this Privacy Policy when the App's functionality, data-handling practices, third-party services, or applicable laws change.</p><p>Updated versions will be published on this page together with an updated “Last updated” date.</p><p>If there are material changes, we will provide appropriate notice where reasonably possible.</p></section>
        <section className="policy-section contact-section" id="contact"><div className="section-heading"><span>13</span><h2>Contact Us</h2></div><p>If you have any questions about this Privacy Policy, Roadi's data practices, or your privacy, please contact us.</p><div className="contact-card"><div className="contact-card-icon"><Mail size={22} /></div><div><span>App</span><strong>Roadi｜Vehicle Companion</strong><span>Developer</span><strong>Billy Song</strong><a href="mailto:attila700@yahoo.com.tw">attila700@yahoo.com.tw <ArrowUpRight size={15} /></a></div></div></section>
        <section className="policy-section" id="scope"><div className="section-heading"><span>14</span><h2>Scope</h2></div><p>This Privacy Policy applies to the Roadi｜Vehicle Companion Android App.</p><p>This policy does not apply to third-party services that you voluntarily use through Roadi, such as Google Drive, email services, messaging applications, or other file-sharing and storage services.</p><p>Those services are governed by their respective privacy policies and terms of service.</p></section>
        <footer className="policy-footer"><span>© 2026 Billy Song. All rights reserved.</span><span>ROADi / LOCAL-FIRST VEHICLE CARE</span></footer>
      </article></div>
    </main>
  </div>;
}
