// Design philosophy: 車庫晨光。Roadi 完整版多語系政策延續溫暖紙白、深墨綠、Safety Orange 與清楚的車庫文件閱讀系統。
import { useEffect } from "react";
import { ArrowUpRight, CarFront, Check, ChevronRight, Mail, ShieldCheck } from "lucide-react";

const SITE_BASE = import.meta.env.BASE_URL;
const ASSET_BASE = "https://roadiprivacy-aekum4hy.manus.space/manus-storage/";
type Language = "vi" | "th" | "ms" | "id";
type Section = { id: string; title: string; paragraphs: string[]; bullets?: string[] };
type Copy = { label: string; title: string; lede: string; intro: string; updated: string; nav: string; localNote: string; switchLabel: string; sections: Section[] };

const localized: Record<Language, Copy> = {
  vi: {
    label: "Chính sách quyền riêng tư", title: "Bảo vệ dữ liệu trong gara của riêng bạn.", lede: "Roadi áp dụng thiết kế Local-First. Dữ liệu xe của bạn chủ yếu được lưu trên thiết bị, đồng thời giải thích rõ cách từng loại thông tin được xử lý.", intro: "Chúng tôi tôn trọng quyền riêng tư của bạn. Chính sách này giải thích cách Roadi xử lý thông tin được tạo ra, nhập vào hoặc sử dụng khi bạn dùng ứng dụng. Roadi không yêu cầu tạo tài khoản và không chủ động tải hồ sơ xe của bạn lên máy chủ do Nhà phát triển vận hành.", updated: "26 tháng 8 năm 2026", nav: "TRÊN TRANG NÀY", localNote: "Dữ liệu của bạn mặc định được lưu cục bộ.", switchLabel: "中文",
    sections: [
      { id: "data", title: "Roadi xử lý những thông tin nào?", paragraphs: ["Để cung cấp các tính năng quản lý xe, theo dõi nhiên liệu, hồ sơ bảo dưỡng, theo dõi chi phí, thống kê và nhắc nhở, bạn có thể tự nguyện nhập hoặc tạo các thông tin sau trong Roadi:"], bullets: ["Tên hoặc biệt danh xe", "Biển số hoặc số xe", "Loại xe", "Ngày mua xe", "Số km khi mua", "Số km hiện tại", "Ngày đổ nhiên liệu", "Lượng nhiên liệu", "Chi phí nhiên liệu", "Tên trạm xăng hoặc cửa hàng", "Hồ sơ bảo dưỡng và sửa chữa", "Hạng mục bảo dưỡng tùy chỉnh", "Chi phí khác liên quan đến xe", "Ghi chú", "Thông tin quản lý xe khác do bạn tự nhập"],},
      { id: "account", title: "Không yêu cầu tài khoản người dùng", paragraphs: ["Roadi không yêu cầu bạn tạo tài khoản hoặc đăng nhập để sử dụng các tính năng chính.", "Roadi không yêu cầu bạn cung cấp tài khoản người dùng, mật khẩu, thông tin đăng nhập hoặc tài khoản mạng xã hội. Vì vậy, Nhà phát triển không duy trì cơ sở dữ liệu tài khoản người dùng." ] },
      { id: "not-collect", title: "Thông tin Roadi không chủ động thu thập", paragraphs: ["Roadi không chủ động thu thập các thông tin sau để cung cấp chức năng chính:"], bullets: ["GPS hoặc vị trí chính xác", "Danh bạ", "Ảnh hoặc video", "Micro hoặc bản ghi âm", "Cuộc gọi hoặc SMS", "Thông tin sức khỏe", "Thông tin thẻ tín dụng hoặc thanh toán", "Mã nhận dạng quảng cáo", "Thông tin tài khoản hoặc đăng nhập"],},
      { id: "local", title: "Lưu trữ dữ liệu cục bộ", paragraphs: ["Roadi lưu dữ liệu xe và hồ sơ liên quan trong cơ sở dữ liệu cục bộ trên thiết bị của bạn.", "Do đó, dữ liệu xe chính của bạn không được lưu trên máy chủ đám mây của Roadi."], bullets: ["Nếu bạn gỡ cài đặt Roadi, xóa dữ liệu ứng dụng, đặt lại thiết bị hoặc mất dữ liệu do thiết bị hay hệ điều hành, dữ liệu chưa được xuất hoặc sao lưu có thể bị mất.", "Chúng tôi khuyến nghị bạn thường xuyên xuất hoặc sao lưu thông tin quan trọng."] },
      { id: "export", title: "Xuất, nhập và chia sẻ dữ liệu", paragraphs: ["Roadi cung cấp tính năng xuất và sao lưu dữ liệu, bao gồm các định dạng như Excel và JSON.", "Khi bạn chủ động sử dụng chức năng chia sẻ, lưu trữ hoặc dịch vụ đám mây của Android hay hệ điều hành khác, dịch vụ bên thứ ba bạn chọn có thể nhận dữ liệu mà bạn chủ động chia sẻ.", "Ví dụ: Google Drive, dịch vụ email, ứng dụng nhắn tin và các dịch vụ lưu trữ hoặc chia sẻ tệp khác.", "Việc truyền dữ liệu này được thực hiện theo thao tác và lựa chọn của bạn. Roadi không tự động tải dữ liệu lên máy chủ do Nhà phát triển vận hành khi bạn sử dụng chức năng xuất. Vui lòng xem chính sách quyền riêng tư của dịch vụ bên thứ ba bạn chọn."] },
      { id: "notification", title: "Thông báo", paragraphs: ["Roadi có thể sử dụng chức năng thông báo của Android để nhắc bạn về các hạng mục bảo dưỡng xe đã đến hạn hoặc sắp đến hạn.", "Nội dung thông báo chủ yếu được tạo từ dữ liệu xe và bảo dưỡng bạn lưu trong Roadi. Roadi không thu thập thông tin cá nhân thông qua thông báo.", "Bạn có thể quản lý quyền thông báo của Roadi trong phần cài đặt hệ thống Android."] },
      { id: "third-party", title: "Phần mềm và dịch vụ bên thứ ba", paragraphs: ["Roadi sử dụng các thư viện phần mềm và thành phần nền tảng cần thiết để hỗ trợ hoạt động ứng dụng, lưu trữ cục bộ, thông báo, xử lý tệp và các chức năng cần thiết khác.", "Roadi không sử dụng dịch vụ quảng cáo bên thứ ba và không bán dữ liệu xe hoặc thông tin cá nhân của bạn. Nếu phần mềm hoặc dịch vụ bên thứ ba thay đổi đáng kể, Chính sách này có thể được cập nhật tương ứng."] },
      { id: "sharing", title: "Chia sẻ và bán dữ liệu", paragraphs: ["Roadi không bán, cho thuê hoặc cung cấp dữ liệu xe của bạn cho bên thứ ba để quảng cáo hoặc tiếp thị.", "Roadi không chủ động chia sẻ hồ sơ xe của bạn với công ty hoặc tổ chức khác.", "Khi bạn chủ động sử dụng chức năng xuất, chia sẻ, lưu trữ hoặc sao lưu, dữ liệu có thể được chuyển đến dịch vụ bên thứ ba bạn chọn. Việc xử lý dữ liệu của dịch vụ đó chịu sự điều chỉnh của chính sách quyền riêng tư và điều khoản dịch vụ tương ứng."] },
      { id: "retention", title: "Lưu giữ và xóa dữ liệu", paragraphs: ["Dữ liệu xe và hồ sơ liên quan chủ yếu được lưu cục bộ trên thiết bị của bạn. Bạn có thể xóa xe và hồ sơ liên quan trực tiếp trong Roadi.", "Để xóa dữ liệu Roadi lưu cục bộ, bạn có thể dùng chức năng Xóa dữ liệu ứng dụng của Android hoặc gỡ cài đặt Roadi.", "Vì Roadi không sử dụng tài khoản người dùng nên không có quy trình xóa tài khoản do Nhà phát triển quản lý. Nhà phát triển không giữ một bản sao riêng của hồ sơ xe Roadi của bạn."] },
      { id: "security", title: "Bảo mật dữ liệu", paragraphs: ["Roadi sử dụng thiết kế lưu trữ cục bộ để giảm nhu cầu truyền dữ liệu xe đến máy chủ bên ngoài.", "Tuy nhiên, không phương thức lưu trữ điện tử nào có thể được đảm bảo an toàn tuyệt đối. Bạn nên bảo vệ thiết bị, hệ điều hành và các tệp đã xuất, đồng thời thường xuyên sao lưu thông tin quan trọng.", "Khi lưu trữ hoặc chia sẻ dữ liệu Roadi đã xuất qua dịch vụ bên thứ ba, tính bảo mật và cách xử lý dữ liệu chịu sự điều chỉnh của biện pháp bảo mật và chính sách quyền riêng tư của bên thứ ba đó."] },
      { id: "children", title: "Quyền riêng tư của trẻ em", paragraphs: ["Roadi không được thiết kế đặc biệt cho trẻ em và không cố ý thu thập thông tin cá nhân của trẻ em."] },
      { id: "changes", title: "Thay đổi Chính sách quyền riêng tư", paragraphs: ["Chúng tôi có thể cập nhật Chính sách này khi chức năng ứng dụng, cách xử lý dữ liệu, dịch vụ bên thứ ba hoặc luật áp dụng thay đổi.", "Phiên bản cập nhật sẽ được đăng trên trang này cùng ngày cập nhật mới. Nếu có thay đổi quan trọng, chúng tôi sẽ thông báo phù hợp trong phạm vi hợp lý."] },
      { id: "contact", title: "Liên hệ với chúng tôi", paragraphs: ["Nếu bạn có câu hỏi về Chính sách này, cách Roadi xử lý dữ liệu hoặc quyền riêng tư của bạn, vui lòng liên hệ với chúng tôi."] },
      { id: "scope", title: "Phạm vi áp dụng", paragraphs: ["Chính sách này áp dụng cho ứng dụng Android Roadi｜Vehicle Companion.", "Chính sách này không áp dụng cho các dịch vụ bên thứ ba mà bạn chủ động sử dụng thông qua Roadi, chẳng hạn như Google Drive, dịch vụ email, ứng dụng nhắn tin hoặc các dịch vụ lưu trữ và chia sẻ tệp khác. Các dịch vụ đó chịu sự điều chỉnh của chính sách quyền riêng tư và điều khoản dịch vụ riêng."] },
    ],
  },
  th: {
    label: "นโยบายความเป็นส่วนตัว", title: "เก็บข้อมูลไว้ในโรงรถของคุณเอง.", lede: "Roadi ใช้แนวคิด Local-First ข้อมูลรถของคุณจะถูกจัดเก็บไว้บนอุปกรณ์เป็นหลัก พร้อมอธิบายอย่างชัดเจนว่าเราใช้ข้อมูลแต่ละประเภทอย่างไร", intro: "เราให้ความสำคัญกับความเป็นส่วนตัวของคุณ นโยบายนี้อธิบายวิธีที่ Roadi จัดการข้อมูลที่เกิดขึ้น ป้อนเข้ามา หรือถูกใช้เมื่อคุณใช้งานแอป Roadi ไม่บังคับให้สร้างบัญชี และจะไม่อัปโหลดข้อมูลรถของคุณไปยังเซิร์ฟเวอร์ที่ผู้พัฒนาดูแลโดยอัตโนมัติ", updated: "26 สิงหาคม 2026", nav: "ในหน้านี้", localNote: "ข้อมูลของคุณจัดเก็บในเครื่องเป็นค่าเริ่มต้น", switchLabel: "中文",
    sections: [
      { id: "data", title: "Roadi จัดการข้อมูลอะไรบ้าง?", paragraphs: ["เพื่อให้บริการจัดการรถ ติดตามการเติมน้ำมัน บันทึกการบำรุงรักษา ติดตามค่าใช้จ่าย สถิติ และการแจ้งเตือน คุณอาจป้อนหรือสร้างข้อมูลต่อไปนี้ด้วยตนเองใน Roadi:"], bullets: ["ชื่อหรือชื่อเล่นรถ", "ทะเบียนรถหรือหมายเลขรถ", "ประเภทรถ", "วันที่ซื้อรถ", "เลขไมล์ตอนซื้อ", "เลขไมล์ปัจจุบัน", "วันที่เติมน้ำมัน", "ปริมาณน้ำมัน", "ค่าเติมน้ำมัน", "ชื่อปั๊มน้ำมันหรือร้านค้า", "ประวัติการบำรุงรักษาและซ่อมแซม", "รายการบำรุงรักษาที่กำหนดเอง", "ค่าใช้จ่ายอื่นเกี่ยวกับรถ", "หมายเหตุ", "ข้อมูลจัดการรถอื่นที่คุณป้อนเอง"] },
      { id: "account", title: "ไม่ต้องมีบัญชีผู้ใช้", paragraphs: ["Roadi ไม่บังคับให้สร้างบัญชีหรือลงชื่อเข้าใช้เพื่อใช้ฟังก์ชันหลัก", "Roadi ไม่ขอให้คุณระบุบัญชีผู้ใช้ รหัสผ่าน ข้อมูลเข้าสู่ระบบ หรือบัญชีโซเชียล ดังนั้นผู้พัฒนาจึงไม่มีฐานข้อมูลบัญชีผู้ใช้ที่ดูแลเอง"] },
      { id: "not-collect", title: "ข้อมูลที่ Roadi ไม่เก็บโดยอัตโนมัติ", paragraphs: ["Roadi ไม่เก็บข้อมูลต่อไปนี้เพื่อการทำงานหลัก:"], bullets: ["GPS หรือตำแหน่งที่แม่นยำ", "รายชื่อติดต่อ", "รูปภาพหรือวิดีโอ", "ไมโครโฟนหรือเสียงบันทึก", "การโทรหรือ SMS", "ข้อมูลสุขภาพ", "ข้อมูลบัตรเครดิตหรือการชำระเงิน", "รหัสโฆษณา", "ข้อมูลบัญชีหรือการเข้าสู่ระบบ"] },
      { id: "local", title: "การจัดเก็บข้อมูลในเครื่อง", paragraphs: ["Roadi จัดเก็บข้อมูลรถและประวัติที่เกี่ยวข้องไว้ในฐานข้อมูลบนอุปกรณ์ของคุณ ข้อมูลรถหลักจึงไม่ได้จัดเก็บอยู่บนเซิร์ฟเวอร์คลาวด์ของ Roadi"], bullets: ["หากคุณถอนการติดตั้ง Roadi ล้างข้อมูลแอป รีเซ็ตอุปกรณ์ หรือข้อมูลหายจากอุปกรณ์หรือระบบปฏิบัติการ ข้อมูลที่ยังไม่ได้ส่งออกหรือสำรองไว้อาจสูญหาย", "เราขอแนะนำให้ส่งออกหรือสำรองข้อมูลสำคัญเป็นประจำ"] },
      { id: "export", title: "การส่งออก นำเข้า และแชร์ข้อมูล", paragraphs: ["Roadi มีฟังก์ชันส่งออกและสำรองข้อมูล เช่น Excel และ JSON", "เมื่อคุณเลือกใช้ฟังก์ชันแชร์ จัดเก็บ หรือบริการคลาวด์ของ Android หรือระบบปฏิบัติการอื่น บริการภายนอกที่คุณเลือกอาจได้รับข้อมูลที่คุณตั้งใจแชร์", "ตัวอย่างเช่น Google Drive บริการอีเมล แอปส่งข้อความ และบริการจัดเก็บหรือแชร์ไฟล์อื่น การส่งข้อมูลนี้เกิดจากการดำเนินการและการเลือกของคุณ Roadi จะไม่อัปโหลดข้อมูลไปยังเซิร์ฟเวอร์ของผู้พัฒนาโดยอัตโนมัติ โปรดดูนโยบายความเป็นส่วนตัวของบริการภายนอกที่คุณเลือก"] },
      { id: "notification", title: "การแจ้งเตือน", paragraphs: ["Roadi อาจใช้ระบบแจ้งเตือนของ Android เพื่อเตือนรายการบำรุงรักษารถที่ถึงกำหนดหรือใกล้ถึงกำหนด เนื้อหาแจ้งเตือนสร้างจากข้อมูลรถและการบำรุงรักษาที่คุณบันทึกไว้ Roadi ไม่เก็บข้อมูลส่วนบุคคลผ่านการแจ้งเตือน", "คุณจัดการสิทธิ์การแจ้งเตือนของ Roadi ได้จากการตั้งค่าระบบ Android"] },
      { id: "third-party", title: "ซอฟต์แวร์และบริการภายนอก", paragraphs: ["Roadi ใช้ไลบรารีซอฟต์แวร์และส่วนประกอบแพลตฟอร์มที่จำเป็นเพื่อรองรับการทำงาน การจัดเก็บในเครื่อง การแจ้งเตือน การจัดการไฟล์ และฟังก์ชันที่จำเป็นอื่น ๆ", "Roadi ไม่ใช้บริการโฆษณาภายนอก และไม่ขายข้อมูลรถหรือข้อมูลส่วนบุคคลของคุณ หากซอฟต์แวร์หรือบริการภายนอกมีการเปลี่ยนแปลงสำคัญ นโยบายนี้อาจได้รับการปรับปรุง"] },
      { id: "sharing", title: "การแชร์และการขายข้อมูล", paragraphs: ["Roadi ไม่ขาย ให้เช่า หรือให้ข้อมูลรถของคุณแก่บุคคลภายนอกเพื่อการโฆษณาหรือการตลาด และไม่แชร์ประวัติรถของคุณกับบริษัทหรือองค์กรอื่นโดยอัตโนมัติ", "เมื่อคุณใช้ฟังก์ชันส่งออก แชร์ จัดเก็บ หรือสำรองข้อมูลด้วยตนเอง ข้อมูลอาจถูกส่งไปยังบริการภายนอกที่คุณเลือก การจัดการข้อมูลของบริการนั้นอยู่ภายใต้นโยบายความเป็นส่วนตัวและข้อกำหนดของบริการนั้น"] },
      { id: "retention", title: "การเก็บรักษาและการลบข้อมูล", paragraphs: ["ข้อมูลรถและประวัติที่เกี่ยวข้องจัดเก็บในเครื่องเป็นหลัก คุณสามารถลบรถและประวัติได้โดยตรงใน Roadi หรือใช้ฟังก์ชันล้างข้อมูลแอปของ Android และถอนการติดตั้ง Roadi", "เนื่องจาก Roadi ไม่ใช้บัญชีผู้ใช้ จึงไม่มีขั้นตอนลบบัญชีที่ผู้พัฒนาดูแล และผู้พัฒนาไม่เก็บสำเนาข้อมูลรถ Roadi ของคุณแยกต่างหาก"] },
      { id: "security", title: "ความปลอดภัยของข้อมูล", paragraphs: ["Roadi ใช้การจัดเก็บในเครื่องเพื่อลดความจำเป็นในการส่งข้อมูลรถไปยังเซิร์ฟเวอร์ภายนอก อย่างไรก็ตาม ไม่มีวิธีจัดเก็บอิเล็กทรอนิกส์ใดรับประกันความปลอดภัยได้อย่างสมบูรณ์", "คุณควรปกป้องอุปกรณ์ ระบบปฏิบัติการ และไฟล์ที่ส่งออก และสำรองข้อมูลสำคัญเป็นประจำ เมื่อใช้บริการภายนอกจัดเก็บหรือแชร์ข้อมูล Roadi ความปลอดภัยและการจัดการข้อมูลจะเป็นไปตามมาตรการและนโยบายของบริการนั้น"] },
      { id: "children", title: "ความเป็นส่วนตัวของเด็ก", paragraphs: ["Roadi ไม่ได้ออกแบบมาโดยเฉพาะสำหรับเด็ก และจะไม่เก็บข้อมูลส่วนบุคคลของเด็กโดยเจตนา"] },
      { id: "changes", title: "การเปลี่ยนแปลงนโยบายความเป็นส่วนตัว", paragraphs: ["เราอาจปรับปรุงนโยบายนี้เมื่อฟังก์ชันของแอป วิธีจัดการข้อมูล บริการภายนอก หรือกฎหมายที่ใช้บังคับมีการเปลี่ยนแปลง เวอร์ชันที่ปรับปรุงแล้วจะเผยแพร่ในหน้านี้พร้อมวันที่อัปเดตใหม่ หากมีการเปลี่ยนแปลงสำคัญ เราจะแจ้งให้ทราบตามสมควร"] },
      { id: "contact", title: "ติดต่อเรา", paragraphs: ["หากมีคำถามเกี่ยวกับนโยบายนี้ วิธีที่ Roadi จัดการข้อมูล หรือสิทธิความเป็นส่วนตัวของคุณ โปรดติดต่อเรา"] },
      { id: "scope", title: "ขอบเขตการใช้งาน", paragraphs: ["นโยบายนี้ใช้กับแอป Android Roadi｜Vehicle Companion และไม่ครอบคลุมบริการภายนอกที่คุณเลือกใช้ผ่าน Roadi เช่น Google Drive อีเมล แอปส่งข้อความ หรือบริการจัดเก็บและแชร์ไฟล์ บริการเหล่านั้นอยู่ภายใต้นโยบายความเป็นส่วนตัวและข้อกำหนดของตนเอง"] },
    ],
  },
  ms: {
    label: "Dasar Privasi", title: "Simpan data dalam garaj anda sendiri.", lede: "Roadi menggunakan pendekatan Local-First. Data kenderaan anda disimpan terutamanya pada peranti anda, dengan penerangan jelas tentang cara setiap maklumat dikendalikan.", intro: "Kami menghormati privasi anda. Dasar ini menerangkan cara Roadi mengendalikan maklumat yang dijana, dimasukkan atau digunakan apabila anda menggunakan aplikasi. Roadi tidak memerlukan akaun dan tidak memuat naik rekod kenderaan anda secara aktif ke pelayan yang dikendalikan oleh Pembangun.", updated: "26 Ogos 2026", nav: "DALAM HALAMAN INI", localNote: "Data anda disimpan secara setempat secara lalai.", switchLabel: "中文",
    sections: [
      { id: "data", title: "Apakah maklumat yang dikendalikan Roadi?", paragraphs: ["Untuk menyediakan pengurusan kenderaan, rekod minyak, penyelenggaraan, perbelanjaan, statistik dan peringatan, anda boleh memasukkan atau mencipta maklumat berikut secara sukarela dalam Roadi:"], bullets: ["Nama atau nama panggilan kenderaan", "Nombor pendaftaran atau nombor kenderaan", "Jenis kenderaan", "Tarikh pembelian", "Bacaan odometer ketika membeli", "Bacaan odometer semasa", "Tarikh mengisi minyak", "Jumlah minyak", "Kos minyak", "Nama stesen minyak atau kedai", "Rekod penyelenggaraan dan pembaikan", "Item penyelenggaraan tersuai", "Perbelanjaan kenderaan lain", "Nota", "Maklumat pengurusan kenderaan lain yang anda masukkan"] },
      { id: "account", title: "Akaun pengguna tidak diperlukan", paragraphs: ["Roadi tidak memerlukan anda mencipta akaun atau log masuk untuk menggunakan fungsi utama. Roadi tidak meminta akaun pengguna, kata laluan, kelayakan log masuk atau akaun media sosial. Oleh itu, Pembangun tidak mengurus pangkalan data akaun pengguna"] },
      { id: "not-collect", title: "Maklumat yang tidak dikumpulkan secara aktif", paragraphs: ["Roadi tidak mengumpulkan maklumat berikut untuk fungsi utama:"], bullets: ["GPS atau lokasi tepat", "Kenalan", "Foto atau video", "Mikrofon atau rakaman audio", "Panggilan atau SMS", "Maklumat kesihatan", "Maklumat kad kredit atau pembayaran", "Pengecam pengiklanan", "Maklumat akaun atau log masuk"] },
      { id: "local", title: "Penyimpanan data setempat", paragraphs: ["Roadi menyimpan data kenderaan dan rekod berkaitan dalam pangkalan data setempat pada peranti anda. Data kenderaan utama anda tidak disimpan pada pelayan awan Roadi."], bullets: ["Jika anda menyahpasang Roadi, memadam data aplikasi, menetapkan semula peranti atau kehilangan data akibat peranti atau sistem operasi, data yang belum dieksport atau disandarkan mungkin hilang.", "Kami mengesyorkan anda mengeksport atau menyandarkan maklumat penting secara berkala."] },
      { id: "export", title: "Eksport, import dan perkongsian data", paragraphs: ["Roadi menyediakan fungsi eksport dan sandaran data, termasuk format seperti Excel dan JSON.", "Apabila anda menggunakan fungsi perkongsian, penyimpanan atau perkhidmatan awan Android atau sistem operasi lain secara sukarela, perkhidmatan pihak ketiga yang dipilih mungkin menerima data yang anda kongsi.", "Contohnya Google Drive, perkhidmatan e-mel, aplikasi mesej dan perkhidmatan penyimpanan atau perkongsian fail lain. Pemindahan ini berlaku melalui tindakan dan pilihan anda. Roadi tidak memuat naik data secara automatik ke pelayan Pembangun. Sila rujuk dasar privasi perkhidmatan pihak ketiga yang dipilih."] },
      { id: "notification", title: "Pemberitahuan", paragraphs: ["Roadi mungkin menggunakan fungsi pemberitahuan Android untuk mengingatkan anda tentang item penyelenggaraan kenderaan yang telah atau hampir tiba masanya. Kandungan pemberitahuan dihasilkan terutamanya daripada data kenderaan dan penyelenggaraan dalam Roadi.", "Roadi tidak mengumpulkan maklumat peribadi melalui pemberitahuan. Anda boleh mengurus kebenaran pemberitahuan Roadi melalui tetapan sistem Android."] },
      { id: "third-party", title: "Perisian dan perkhidmatan pihak ketiga", paragraphs: ["Roadi menggunakan perpustakaan perisian dan komponen platform yang diperlukan untuk menyokong operasi aplikasi, penyimpanan setempat, pemberitahuan, pengendalian fail dan fungsi lain yang diperlukan.", "Roadi tidak menggunakan perkhidmatan pengiklanan pihak ketiga dan tidak menjual data kenderaan atau maklumat peribadi anda. Jika perkhidmatan pihak ketiga berubah dengan ketara, dasar ini mungkin dikemas kini."] },
      { id: "sharing", title: "Perkongsian dan penjualan data", paragraphs: ["Roadi tidak menjual, menyewa atau memberikan data kenderaan anda kepada pihak ketiga untuk tujuan pengiklanan atau pemasaran, dan tidak berkongsi rekod anda secara aktif dengan syarikat atau organisasi lain.", "Apabila anda menggunakan fungsi eksport, perkongsian, penyimpanan atau sandaran secara sukarela, data mungkin dipindahkan kepada perkhidmatan pihak ketiga yang anda pilih. Pengendalian data tersebut tertakluk pada dasar privasi dan syarat perkhidmatan pihak berkenaan."] },
      { id: "retention", title: "Penyimpanan dan pemadaman data", paragraphs: ["Data kenderaan dan rekod berkaitan disimpan terutamanya pada peranti anda. Anda boleh memadam kenderaan dan rekod secara terus dalam Roadi, atau menggunakan fungsi Clear App Data Android dan menyahpasang Roadi.", "Oleh kerana Roadi tidak menggunakan akaun pengguna, tiada proses pemadaman akaun yang diuruskan Pembangun. Pembangun tidak menyimpan salinan berasingan rekod kenderaan Roadi anda."] },
      { id: "security", title: "Keselamatan data", paragraphs: ["Roadi menggunakan reka bentuk penyimpanan setempat untuk mengurangkan keperluan menghantar data kenderaan ke pelayan luar. Walau bagaimanapun, tiada kaedah penyimpanan elektronik yang boleh dijamin selamat sepenuhnya.", "Anda hendaklah melindungi peranti, sistem operasi dan fail yang dieksport serta membuat sandaran maklumat penting secara berkala. Apabila data Roadi disimpan atau dikongsi melalui pihak ketiga, keselamatan dan pengendaliannya tertakluk pada amalan keselamatan dan dasar privasi pihak tersebut."] },
      { id: "children", title: "Privasi kanak-kanak", paragraphs: ["Roadi tidak direka khusus untuk kanak-kanak dan tidak mengumpulkan maklumat peribadi kanak-kanak dengan sengaja"] },
      { id: "changes", title: "Perubahan Dasar Privasi ini", paragraphs: ["Kami mungkin mengemas kini dasar ini apabila fungsi aplikasi, amalan pengendalian data, perkhidmatan pihak ketiga atau undang-undang yang terpakai berubah. Versi yang dikemas kini akan diterbitkan pada halaman ini bersama tarikh kemas kini baharu. Jika terdapat perubahan material, kami akan memberikan notis yang sesuai setakat yang munasabah."] },
      { id: "contact", title: "Hubungi kami", paragraphs: ["Jika anda mempunyai soalan tentang dasar ini, amalan data Roadi atau privasi anda, sila hubungi kami"] },
      { id: "scope", title: "Skop", paragraphs: ["Dasar ini terpakai kepada aplikasi Android Roadi｜Vehicle Companion. Dasar ini tidak terpakai kepada perkhidmatan pihak ketiga yang anda gunakan secara sukarela melalui Roadi seperti Google Drive, e-mel, aplikasi mesej atau perkhidmatan perkongsian dan penyimpanan fail. Perkhidmatan tersebut tertakluk pada dasar privasi dan syarat perkhidmatan masing-masing."] },
    ],
  },
  id: {
    label: "Kebijakan Privasi", title: "Simpan data di garasi Anda sendiri.", lede: "Roadi menggunakan pendekatan Local-First. Data kendaraan Anda terutama disimpan di perangkat, dengan penjelasan yang jelas tentang cara setiap informasi ditangani.", intro: "Kami menghargai privasi Anda. Kebijakan ini menjelaskan cara Roadi menangani informasi yang dibuat, dimasukkan, atau digunakan saat Anda memakai aplikasi. Roadi tidak mewajibkan pembuatan akun dan tidak secara aktif mengunggah catatan kendaraan Anda ke server yang dioperasikan Pengembang.", updated: "26 Agustus 2026", nav: "DI HALAMAN INI", localNote: "Data Anda disimpan secara lokal secara default.", switchLabel: "中文",
    sections: [
      { id: "data", title: "Informasi apa yang ditangani Roadi?", paragraphs: ["Untuk menyediakan pengelolaan kendaraan, pencatatan bahan bakar, perawatan, pengeluaran, statistik, dan pengingat, Anda dapat memasukkan atau membuat informasi berikut secara sukarela di Roadi:"], bullets: ["Nama atau nama panggilan kendaraan", "Nomor pelat atau nomor kendaraan", "Jenis kendaraan", "Tanggal pembelian", "Jarak tempuh saat pembelian", "Jarak tempuh saat ini", "Tanggal pengisian bahan bakar", "Jumlah bahan bakar", "Biaya bahan bakar", "Nama SPBU atau toko", "Catatan perawatan dan perbaikan", "Item perawatan khusus", "Pengeluaran kendaraan lainnya", "Catatan", "Informasi pengelolaan kendaraan lain yang Anda masukkan"] },
      { id: "account", title: "Tidak memerlukan akun pengguna", paragraphs: ["Roadi tidak mengharuskan Anda membuat akun atau masuk untuk menggunakan fitur utama. Roadi tidak meminta akun pengguna, kata sandi, kredensial masuk, atau akun media sosial. Karena itu, Pengembang tidak mengelola basis data akun pengguna"] },
      { id: "not-collect", title: "Informasi yang tidak dikumpulkan secara aktif", paragraphs: ["Roadi tidak secara aktif mengumpulkan informasi berikut untuk fungsi utama:"], bullets: ["GPS atau lokasi tepat", "Kontak", "Foto atau video", "Mikrofon atau rekaman audio", "Panggilan atau SMS", "Informasi kesehatan", "Informasi kartu kredit atau pembayaran", "Pengenal iklan", "Informasi akun atau login"] },
      { id: "local", title: "Penyimpanan data lokal", paragraphs: ["Roadi menyimpan data kendaraan dan catatan terkait dalam basis data lokal di perangkat Anda. Data kendaraan utama Anda tidak disimpan di server cloud Roadi."], bullets: ["Jika Anda menghapus instalasi Roadi, menghapus data aplikasi, mengatur ulang perangkat, atau kehilangan data karena perangkat atau sistem operasi, data yang belum diekspor atau dicadangkan dapat hilang.", "Kami menyarankan Anda mengekspor atau mencadangkan informasi penting secara berkala."] },
      { id: "export", title: "Ekspor, impor, dan berbagi data", paragraphs: ["Roadi menyediakan fitur ekspor dan pencadangan data, termasuk format seperti Excel dan JSON.", "Saat Anda secara sukarela menggunakan fitur berbagi, penyimpanan, atau layanan cloud Android atau sistem operasi lain, layanan pihak ketiga yang Anda pilih dapat menerima data yang Anda bagikan.", "Contohnya Google Drive, layanan email, aplikasi pesan, dan layanan penyimpanan atau berbagi file lainnya. Transfer ini terjadi berdasarkan tindakan dan pilihan Anda. Roadi tidak otomatis mengunggah data ke server Pengembang saat Anda menggunakan fungsi ekspor. Silakan lihat kebijakan privasi layanan pihak ketiga yang dipilih."] },
      { id: "notification", title: "Notifikasi", paragraphs: ["Roadi dapat menggunakan fitur notifikasi Android untuk mengingatkan Anda tentang item perawatan kendaraan yang sudah atau akan jatuh tempo. Isi notifikasi terutama dibuat dari data kendaraan dan perawatan yang tersimpan di Roadi.", "Roadi tidak mengumpulkan informasi pribadi melalui notifikasi. Anda dapat mengatur izin notifikasi Roadi melalui pengaturan sistem Android."] },
      { id: "third-party", title: "Perangkat lunak dan layanan pihak ketiga", paragraphs: ["Roadi menggunakan pustaka perangkat lunak dan komponen platform yang diperlukan untuk mendukung operasi aplikasi, penyimpanan lokal, notifikasi, pemrosesan file, dan fungsi lain yang diperlukan.", "Roadi tidak menggunakan layanan iklan pihak ketiga dan tidak menjual data kendaraan atau informasi pribadi Anda. Jika perangkat lunak atau layanan pihak ketiga berubah secara material, Kebijakan ini dapat diperbarui."] },
      { id: "sharing", title: "Berbagi dan penjualan data", paragraphs: ["Roadi tidak menjual, menyewakan, atau memberikan data kendaraan Anda kepada pihak ketiga untuk tujuan iklan atau pemasaran, dan tidak secara aktif membagikan catatan kendaraan Anda kepada perusahaan atau organisasi lain.", "Saat Anda secara sukarela menggunakan fungsi ekspor, berbagi, penyimpanan, atau pencadangan, data dapat dikirim ke layanan pihak ketiga yang Anda pilih. Penanganan data oleh layanan tersebut diatur oleh kebijakan privasi dan ketentuan layanan masing-masing."] },
      { id: "retention", title: "Penyimpanan dan penghapusan data", paragraphs: ["Data kendaraan dan catatan terkait terutama disimpan secara lokal di perangkat Anda. Anda dapat menghapus kendaraan dan catatan langsung di Roadi, menggunakan fungsi Clear App Data Android, atau menghapus instalasi Roadi.", "Karena Roadi tidak menggunakan akun pengguna, tidak ada proses penghapusan akun yang dikelola Pengembang. Pengembang tidak menyimpan salinan terpisah dari catatan kendaraan Roadi Anda."] },
      { id: "security", title: "Keamanan data", paragraphs: ["Roadi menggunakan desain penyimpanan lokal untuk mengurangi kebutuhan mengirimkan data kendaraan ke server eksternal. Namun, tidak ada metode penyimpanan elektronik yang dapat dijamin sepenuhnya aman.", "Anda harus melindungi perangkat, sistem operasi, dan file yang diekspor serta mencadangkan informasi penting secara berkala. Saat menyimpan atau membagikan data Roadi melalui layanan pihak ketiga, keamanan dan penanganannya diatur oleh praktik keamanan dan kebijakan privasi pihak tersebut."] },
      { id: "children", title: "Privasi anak-anak", paragraphs: ["Roadi tidak dirancang khusus untuk anak-anak dan tidak dengan sengaja mengumpulkan informasi pribadi dari anak-anak"] },
      { id: "changes", title: "Perubahan Kebijakan Privasi ini", paragraphs: ["Kami dapat memperbarui Kebijakan ini ketika fungsi aplikasi, praktik penanganan data, layanan pihak ketiga, atau hukum yang berlaku berubah. Versi yang diperbarui akan dipublikasikan di halaman ini bersama tanggal pembaruan baru. Jika terdapat perubahan material, kami akan memberikan pemberitahuan yang sesuai sejauh wajar dilakukan."] },
      { id: "contact", title: "Hubungi kami", paragraphs: ["Jika Anda memiliki pertanyaan tentang Kebijakan ini, praktik data Roadi, atau privasi Anda, silakan hubungi kami"] },
      { id: "scope", title: "Ruang lingkup", paragraphs: ["Kebijakan ini berlaku untuk aplikasi Android Roadi｜Vehicle Companion. Kebijakan ini tidak berlaku untuk layanan pihak ketiga yang Anda gunakan secara sukarela melalui Roadi, seperti Google Drive, email, aplikasi pesan, atau layanan berbagi dan penyimpanan file lainnya. Layanan tersebut diatur oleh kebijakan privasi dan ketentuan layanan masing-masing."] },
    ],
  },
};

const navItems = ["data", "account", "not-collect", "local", "export", "notification", "third-party", "sharing", "retention", "security", "children", "changes", "contact", "scope"];
const navNumbers = ["01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14"];
const languagePaths = { vi: "vi", th: "th", ms: "ms", id: "id" } as const;

function BulletList({ items }: { items: string[] }) { return <ul className="policy-list">{items.map((item) => <li key={item}><span className="list-check"><Check size={13} strokeWidth={3} /></span><span>{item}</span></li>)}</ul>; }

export default function RoadiLocalizedPolicy({ language }: { language: Language }) {
  const copy = localized[language];
  useEffect(() => { document.title = `Roadi｜${copy.label}`; }, [copy.label]);
  const jumpTo = (id: string) => document.getElementById(id)?.scrollIntoView({ behavior: "smooth", block: "start" });
  const currentPath = `${SITE_BASE}${languagePaths[language]}/`;
  return <div className="site-shell">
    <header className="topbar"><a className="brand" href={SITE_BASE} aria-label="Roadi home"><img src={`${ASSET_BASE}roadi-mark_5db22b61.png`} alt="" className="brand-mark" /><span><strong>Roadi</strong><small>Vehicle Companion</small></span></a><div className="topbar-meta"><span className="status-dot" /> {copy.label} <span className="meta-divider" /> 2026.08 <a className="language-switch" href={`${SITE_BASE}en/`}>EN</a></div><div className="language-links" aria-label="Languages">{Object.entries(languagePaths).map(([code, path]) => <a key={code} href={`${SITE_BASE}${path}/`} className={code === language ? "active" : ""}>{code.toUpperCase()}</a>)}</div></header>
    <main id="top"><section className="hero-section"><div className="hero-copy"><div className="eyebrow"><span className="eyebrow-line" /> DOCUMENT / PRIVACY</div><h1>{copy.title}</h1><p className="hero-lede">{copy.lede}</p><div className="hero-details"><span>Last updated</span><strong>{copy.updated}</strong><span className="detail-rule" /><span>Platform</span><strong>Android App</strong></div></div><div className="hero-visual" aria-hidden="true"><img src={`${ASSET_BASE}roadi-policy-hero_8d71e61f.jpg`} alt="" /><div className="hero-stamp">LOCAL<br /><span>FIRST</span></div><div className="road-mark" /></div></section>
      <section className="intro-band"><div className="intro-icon"><ShieldCheck size={25} /></div><p><strong>{copy.label}.</strong> {copy.intro}</p><ArrowUpRight size={21} className="intro-arrow" /></section>
      <div className="policy-layout"><aside className="section-nav" aria-label={copy.nav}><div className="nav-kicker">{copy.nav}</div><div className="nav-list">{copy.sections.map((section, index) => <button key={section.id} onClick={() => jumpTo(section.id)}><span>{navNumbers[index]}</span>{section.title}<ChevronRight size={14} /></button>)}</div><div className="nav-note"><CarFront size={17} /><span>{copy.localNote}</span></div></aside>
        <article className="policy-content"><div className="content-label"><span>ROADi / PRIVACY POLICY</span><span>REV. 01 / {language.toUpperCase()}</span></div>{copy.sections.map((section, index) => <section className="policy-section" id={section.id} key={section.id}><div className="section-heading"><span>{navNumbers[index]}</span><h2>{section.title}</h2></div>{section.paragraphs.map((p) => <p key={p}>{p}</p>)}{section.bullets && <BulletList items={section.bullets} />}{section.id === "contact" && <div className="contact-card"><div className="contact-card-icon"><Mail size={22} /></div><div><span>App</span><strong>Roadi｜Vehicle Companion</strong><span>Developer</span><strong>Billy Song</strong><a href="mailto:attila700@yahoo.com.tw">attila700@yahoo.com.tw <ArrowUpRight size={15} /></a></div></div>}</section>)}<footer className="policy-footer"><span>© 2026 Billy Song. All rights reserved.</span><span>ROADi / LOCAL-FIRST VEHICLE CARE</span></footer></article></div></main>
  </div>;
}
